//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLWeather.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMLWeather.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Background {
            get {
                object obj = ResourceManager.GetObject("Blue_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloudy {
            get {
                object obj = ResourceManager.GetObject("Cloudy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grey_Background {
            get {
                object obj = ResourceManager.GetObject("Grey_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mist {
            get {
                object obj = ResourceManager.GetObject("Mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rain3 {
            get {
                object obj = ResourceManager.GetObject("Rain3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rainy {
            get {
                object obj = ResourceManager.GetObject("Rainy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red_Background {
            get {
                object obj = ResourceManager.GetObject("Red_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Snowy {
            get {
                object obj = ResourceManager.GetObject("Snowy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sunny {
            get {
                object obj = ResourceManager.GetObject("Sunny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thunderstorms {
            get {
                object obj = ResourceManager.GetObject("Thunderstorms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;current&gt;
        ///	&lt;city id=&quot;6157977&quot; name=&quot;Stratford&quot;&gt;
        ///		&lt;coord lon=&quot;-80.95&quot; lat=&quot;43.37&quot;&gt;&lt;/coord&gt;
        ///		&lt;country&gt;CA&lt;/country&gt;
        ///		&lt;sun rise=&quot;2017-04-19T10:33:15&quot; set=&quot;2017-04-20T00:12:51&quot;&gt;&lt;/sun&gt;
        ///	&lt;/city&gt;
        ///	&lt;temperature value=&quot;18.05&quot; min=&quot;17&quot; max=&quot;19&quot; unit=&quot;metric&quot;&gt;&lt;/temperature&gt;
        ///	&lt;humidity value=&quot;88&quot; unit=&quot;%&quot;&gt;&lt;/humidity&gt;
        ///	&lt;pressure value=&quot;1015&quot; unit=&quot;hPa&quot;&gt;&lt;/pressure&gt;
        ///	&lt;wind&gt;
        ///		&lt;speed value=&quot;4.1&quot; name=&quot;Gentle Breeze&quot;&gt;&lt;/speed&gt;
        ///		&lt;gusts&gt;&lt;/gusts&gt;
        ///		&lt;direction value=&quot;250&quot; code=&quot;WSW&quot; name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeatherData {
            get {
                return ResourceManager.GetString("WeatherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;weatherdata&gt;
        ///	&lt;location&gt;
        ///		&lt;name&gt;Stratford&lt;/name&gt;
        ///		&lt;type&gt;&lt;/type&gt;
        ///		&lt;country&gt;CA&lt;/country&gt;
        ///		&lt;timezone&gt;&lt;/timezone&gt;
        ///		&lt;location altitude=&quot;0&quot; latitude=&quot;43.3668&quot; longitude=&quot;-80.9498&quot; geobase=&quot;geonames&quot; geobaseid=&quot;6157977&quot;&gt;&lt;/location&gt;
        ///	&lt;/location&gt;
        ///	&lt;credit&gt;&lt;/credit&gt;
        ///	&lt;meta&gt;
        ///		&lt;lastupdate&gt;&lt;/lastupdate&gt;
        ///		&lt;calctime&gt;0.2501&lt;/calctime&gt;
        ///		&lt;nextupdate&gt;&lt;/nextupdate&gt;
        ///	&lt;/meta&gt;
        ///	&lt;sun rise=&quot;2017-04-19T10:33:15&quot; set=&quot;2017-04-20T00:12:50&quot;&gt;&lt;/sun&gt;
        ///	&lt;forecast&gt;
        ///		&lt;time day=&quot;2017-04-19&quot;&gt;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeatherData7Day {
            get {
                return ResourceManager.GetString("WeatherData7Day", resourceCulture);
            }
        }
    }
}
